name: Check failed cycles and samples for bedbase

on:
  schedule:
    # run every 2d day at 11:00
    - cron: '0 11 1/2 * *'
  workflow_dispatch:
    inputs: null


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi

      - name: Check 1 cycle before
        run: python metageo_pephub/main.py --target bedbase --function run_checker --host ${{ secrets.HOST }} --db ${{ secrets.DB }} --user ${{ secrets.USER }} --password ${{ secrets.PASSWORD }} --period 2 --cycle-count 1

      - name: Check 2 cycle before
        run: python metageo_pephub/main.py --target bedbase --function run_checker --host ${{ secrets.HOST }} --db ${{ secrets.DB }} --user ${{ secrets.USER }} --password ${{ secrets.PASSWORD }} --period 2 --cycle-count 2

      - name: Check 3 cycle before
        run: python metageo_pephub/main.py --target bedbase --function run_checker --host ${{ secrets.HOST }} --db ${{ secrets.DB }} --user ${{ secrets.USER }} --password ${{ secrets.PASSWORD }} --period 2 --cycle-count 3

      - name: Check 4 cycle before
        run: python metageo_pephub/main.py --target bedbase --function run_checker --host ${{ secrets.HOST }} --db ${{ secrets.DB }} --user ${{ secrets.USER }} --password ${{ secrets.PASSWORD }} --period 2 --cycle-count 4

      - name: Check 5 cycle before
        run: python metageo_pephub/main.py --target bedbase --function run_checker --host ${{ secrets.HOST }} --db ${{ secrets.DB }} --user ${{ secrets.USER }} --password ${{ secrets.PASSWORD }} --period 2 --cycle-count 5
