name: Clean history table. With providing number of days to keep in the history.

on:
  schedule:
    # run every 10 days at 10:00
    - cron: '0 10 1/10 * *'
  workflow_dispatch:
    inputs: null


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.12" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: python -m pip install .

      - name: Upload Projects of specified period
        run: geopephub clean-history --days 365
        # By default it will keep 365 days of history
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
