name: Create Log table

on:
  workflow_dispatch:
    inputs: null


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi

      - name: Run upload
        run: python src/create_log_table.py --host ${{ secrets.HOST }} --db ${{ secrets.DB }} --user ${{ secrets.USER }} --password ${{ secrets.PASSWORD }}
