name: geo projects to s3

on:
  schedule:
    # run every day at 11:00
    - cron: '0 11 * * *'
  workflow_dispatch:
    inputs: null



jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: python -m pip install .

      - name: Calculate yesterday's date and set it as an environment variable
        run: |
          $NOW = (Get-Date).AddDays(-1).ToString("yyyy-MM-dd")
          echo "YESTERDAY=$NOW" >> $env:GITHUB_ENV

      - name: Add to the queue
        run: geopephub download --namespace geo --limit 5 --start-period ${{ env.YESTERDAY }} --destination s3://pephub
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
