name: Run project uploader for specified period

on:
  workflow_dispatch:
    inputs:
      start_period:
        description: 'start_period (Earlier in the calender) [e.g. "2020/02/25"]'
        required: true
      end_period:
        description: 'end period (Later in the calender) [e.g. "2021/05/27"]'
        required: true
      target:
        description: 'namespace target. ["bedbase", "geo"]'
        required: false
        default: "geo"


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.12" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: python -m pip install .

      - name: Upload Projects of specified period
        run: geopephub check-by-date --target ${{ inputs.target }} --start-period ${{ inputs.start_period }} --end-period ${{ inputs.end_period }}
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
