name: Upload project

on:
  schedule:
    - cron: '50 21 * * 2'
    - cron: '00 22 * * 2'


jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi

      - name: Run upload
        run: python geo_pipeline_script.py --namespace test --tag test2 --host xxx --db xxx --user xxx --password xxx
