name: Upload project

on:
  schedule:
    # run every monday at 00:05
    - cron: '5 0 * * MON'
  workflow_dispatch:
    inputs: null


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi

      - name: Run upload
        run: python geo_pipeline_script.py --namespace test --tag test2 --host ${{ secrets.HOST }} --db ${{ secrets.DB }} --user ${{ secrets.USER }} --password ${{ secrets.PASSWORD }} > upload_logs/upload_"${{ steps.current-time.outputs.formattedTime }}".log

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: commit
        run: |
          git add upload_logs/upload_${{ steps.date.outputs.date }}.log
          git commit -m "new date commit"
          git push origin main